version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5435:5432"  # Corrección del puerto
    environment:
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
